spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/kfarm
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

#  #??? ??? ??
#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace #??????


jwt:
  secret:
    key : 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
